Script started on Mon 08 Dec 2014 01:10:29 PM PST
[?1034h[dustlee@bpm root]$ sys161 kernel
sys161: System/161 release 1.99.08_uwcse, compiled Sep 25 2014 10:38:57

OS/161 base system version 1.99.07
Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST3 #89)

224k physical memory available
1 pages (672 bytest) occupied for the coremap
coremap selftest passed 
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
OS/161 kernel [? for menu]: s
(program name unknown): Timing enabled.
OS/161$ tsetbin/matmult              estbin/matmult
matmult finished.
answer is: 8772192 (should be 8772192)
Passed.
(program name unknown): subprocess time: 75.470930103 seconds
OS/161$ testbin/amtm    matmult
matmult finished.
answer is: 8772192 (should be 8772192)
Passed.
(program name unknown): subprocess time: 77.528551802 seconds
OS/161$ sbin/poweroff
Shutting down.
The system is halted.
sys161: 4689923790 cycles (1265825906 run, 3424097884 global-idle)
sys161:   cpu0: 416866991 kern, 13179065 user, 0 idle; 335243 ll, 335243/0 sc, 899398 sync
sys161: 49044 irqs 12911 exns 8424r/13984w disk 84r/1132w console 35r/0w/9m emufs 0r/0w net
sys161: Elapsed real time: 57.258272 seconds (81.9082 mhz)
sys161: Elapsed virtual time: 187.601591039 seconds (25 mhz)
[dustlee@bpm root]$ exit
exit

Script done on Mon 08 Dec 2014 01:11:38 PM PST
